# CodeRabbit configuration
# See: https://docs.coderabbit.ai/guides/review-instructions/

early_access: true

issue_enrichment:
  planning:
    enabled: true

reviews:
  request_changes_workflow: true
  high_level_summary: true
  poem: true
  review_status: true
  collapse_walkthrough: false
  auto_review:
    enabled: true
    drafts: false
  pre_merge_checks:
    custom_checks:
      - mode: error
        name: shell-check
        instructions: |
          - Always check if the shell scripts are valid and sytactically correct.
          - Make sure there are examples for all the supported shells, such as bash, zsh, fish, etc.

chat:
  auto_reply: true
